config/routes.rb
Rails.application.routes.draw do
  get 'campaign/index'

  get 'campaign/candidate_lists'

  root 'campaign#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController
  def index
  	@campaign = Campaign.group("campaign")
  end

  def candidate_lists
  	@campaign = params[:campaign]
  	@candidates = Campaign.where(:campaign => @campaign).group("choice")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
	def score(campaign,choice)
		scores =  Campaign.where(:campaign=>campaign , :choice=>choice,:validity=>"during")
		return scores.count
	end 
	def number_of_message(campaign,choice)
		scores =  Campaign.where(:campaign=>campaign , :choice=>choice,:validity=>'pre' || 'post')
		return scores.count
	end	
end

app/views/campaign/candidate_lists.html.erb
<div clas="row">
	<div class="large-12 columns">
		<h1>
			<a>
					Candidates List
			</a>
		</h1>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Candidate Name
			</th>
			<th>
				
			 Scores
			</th>			
			<th> 
				The Number of messages(Not counted as score)
			</th>			
			</tr>
		</thead>
		<tbody>
		<%@candidates.each do |candidates|%>
		<tr>
			<td>
				<%=candidates.choice%>
			</td>
			<td>
				<%=score(candidates.campaign,candidates.choice)%>
			</td>
			<td>
				<%=number_of_message(candidates.campaign,candidates.choice)%>
			</td>				
												
		</tr>
		<%end%>

		</tbody>
		</table> 
	</div>

</div>

app/views/campaign/index.html.erb
<div clas="row">
	<div class="large-12 columns">
		<h1>
			<a>
					Campaign List
			</a>
		</h1>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Campaigns
			</th>
			<th>
				

			</th>			
							
			</tr>
		</thead>
		<tbody>
		<%@campaign.each do |campaign|%>
		<tr>
			<td>
				<%=campaign.campaign.titleize%>
			</td>
			<td>
				<%=link_to "Candidates List" ,campaign_candidate_lists_path(:campaign=>campaign.campaign),:class=>"large-6 button success"%>
			</td>	
												
		</tr>
		<%end%>

		</tbody>
		</table> 
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Voting System" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="row">
    <nav class="top-bar" data-topbar role="navigation">
     <ul class="title-area"> 
        <li class="name"> 
            <h1>
              <a href="/">
                TV SMS voting campaigns
              </a>
            </h1>
        </li>
     </ul>
    </nav>
      <div class="row">
        <%= yield %>
      </div>
      <%= javascript_include_tag "application" %>
  </div>
  </body>
</html>